'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import LayoutTaiKhoan from '@/components/Layout/LayoutTaiKhoan';
import { hienToast } from '@/components/Toast/Toast';
import { taoSupabaseClient } from '@/lib/supabase/client';
import { kiemTraSoDienThoai } from '@/lib/utils';
import type { Profile } from '@/types';

export default function TaiKhoanPage() {
  const router = useRouter();
  const supabase = taoSupabaseClient();

  const [profile, setProfile] = useState<Profile | null>(null);
  const [hoTen, setHoTen] = useState('');
  const [soDienThoai, setSoDienThoai] = useState('');
  const [email, setEmail] = useState('');
  const [dangCapNhat, setDangCapNhat] = useState(false);
  const [dangTai, setDangTai] = useState(true);

  // Doi mat khau
  const [matKhauCu, setMatKhauCu] = useState('');
  const [matKhauMoi, setMatKhauMoi] = useState('');
  const [xacNhanMatKhauMoi, setXacNhanMatKhauMoi] = useState('');
  const [hienMatKhauCu, setHienMatKhauCu] = useState(false);
  const [hienMatKhauMoi, setHienMatKhauMoi] = useState(false);
  const [hienXacNhan, setHienXacNhan] = useState(false);
  const [dangDoiMatKhau, setDangDoiMatKhau] = useState(false);
  const [emailTaiKhoan, setEmailTaiKhoan] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<'thong_tin' | 'doi_mat_khau'>('thong_tin');

  // Xoa tai khoan (Chi Sinh vien va Chu tro)
  const [hienModalXoa, setHienModalXoa] = useState(false);
  const [dangXoaTaiKhoan, setDangXoaTaiKhoan] = useState(false);

  useEffect(() => {
    async function taiProfile() {
      setDangTai(true);
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) {
        router.push('/dang-nhap');
        return;
      }

      const { data: p } = await supabase
        .from('profiles')
        .select('*')
        .eq('id', user.id)
        .single();

      if (p) {
        setProfile(p as Profile);
        setHoTen(p.ho_ten);
        setSoDienThoai(p.so_dien_thoai);
        // Neu email la phu mien tu dong sdt@gmail.com thi de trong cho nguoi dung tu cap nhat email thuc
        const emailHienTai = p.email || '';
        const isAutoGeneratedEmail = emailHienTai === `${p.so_dien_thoai}@gmail.com`;
        setEmail(isAutoGeneratedEmail ? '' : emailHienTai);
        // Luu email auth (dung de xac minh mat khau cu)
        setEmailTaiKhoan(user.email || null);
      }
      setDangTai(false);
    }
    taiProfile();
  }, []);

  async function xuLyCapNhat(e: React.FormEvent) {
    e.preventDefault();
    if (!profile) return;

    const sdtChuan = soDienThoai.trim();
    if (!kiemTraSoDienThoai(sdtChuan)) {
      hienToast('Số điện thoại không hợp lệ (phải gồm 10 chữ số, bắt đầu từ 03, 05, 07, 08, 09)', 'loi');
      return;
    }

    setDangCapNhat(true);

    // Kiem tra SDT neu co thay doi
    if (sdtChuan !== profile.so_dien_thoai) {
      const { data: tonTaiSDT } = await supabase
        .from('profiles')
        .select('id')
        .eq('so_dien_thoai', sdtChuan)
        .neq('id', profile.id)
        .maybeSingle();

      if (tonTaiSDT) {
        hienToast('Số điện thoại này đã được sử dụng bởi tài khoản khác', 'loi');
        setDangCapNhat(false);
        return;
      }
    }

    const emailChuan = email.trim();

    const { error } = await supabase
      .from('profiles')
      .update({
        ho_ten: hoTen.trim(),
        so_dien_thoai: sdtChuan,
        email: emailChuan || null,
      })
      .eq('id', profile.id);

    setDangCapNhat(false);

    if (error) {
      hienToast('Không thể cập nhật thông tin: ' + error.message, 'loi');
    } else {
      setProfile({
        ...profile,
        ho_ten: hoTen.trim(),
        so_dien_thoai: sdtChuan,
        email: emailChuan || null,
      });
      hienToast('Đã cập nhật thông tin cá nhân thành công!', 'thanh_cong');
    }
  }

  // Doi mat khau
  async function xuLyDoiMatKhau(e: React.FormEvent) {
    e.preventDefault();
    if (!emailTaiKhoan) {
      hienToast('Không tìm thấy thông tin tài khoản', 'loi');
      return;
    }

    if (matKhauMoi.length < 6) {
      hienToast('Mật khẩu mới phải có ít nhất 6 ký tự', 'loi');
      return;
    }

    if (matKhauMoi !== xacNhanMatKhauMoi) {
      hienToast('Mật khẩu xác nhận không khớp với mật khẩu mới', 'loi');
      return;
    }

    setDangDoiMatKhau(true);

    try {
      // Buoc 1: Xac minh mat khau cu bang signInWithPassword
      const { error: loginErr } = await supabase.auth.signInWithPassword({
        email: emailTaiKhoan,
        password: matKhauCu,
      });

      if (loginErr) {
        hienToast('Mật khẩu cũ không chính xác', 'loi');
        setDangDoiMatKhau(false);
        return;
      }

      // Buoc 2: Cap nhat mat khau moi
      const { error: updateErr } = await supabase.auth.updateUser({
        password: matKhauMoi,
      });

      if (updateErr) {
        hienToast('Không thể đổi mật khẩu: ' + updateErr.message, 'loi');
        return;
      }

      setMatKhauCu('');
      setMatKhauMoi('');
      setXacNhanMatKhauMoi('');
      hienToast('Đổi mật khẩu thành công!', 'thanh_cong');
    } catch (err: any) {
      hienToast('Lỗi: ' + err.message, 'loi');
    } finally {
      setDangDoiMatKhau(false);
    }
  }

  // Xoa tai khoan
  async function xuLyXoaTaiKhoan() {
    setDangXoaTaiKhoan(true);
    try {
      const res = await fetch('/api/auth/xoa-tai-khoan', {
        method: 'POST',
      });
      const data = await res.json();
      if (!res.ok) {
        hienToast(data.loi || 'Không thể xóa tài khoản', 'loi');
        setDangXoaTaiKhoan(false);
        setHienModalXoa(false);
        return;
      }
      hienToast('Đã xóa tài khoản thành công', 'thanh_cong');
      router.push('/dang-nhap');
    } catch (err: any) {
      hienToast(err.message || 'Lỗi hệ thống khi xóa tài khoản', 'loi');
      setDangXoaTaiKhoan(false);
      setHienModalXoa(false);
    }
  }

  if (dangTai) {
    return (
      <LayoutTaiKhoan profile={profile}>
        <div style={{ textAlign: 'center', padding: '60px 0' }}>Đang tải thông tin tài khoản...</div>
      </LayoutTaiKhoan>
    );
  }

  return (
    <LayoutTaiKhoan profile={profile}>
      <div style={{ maxWidth: '560px', margin: '0 auto' }}>
        {/* SUB TABS (THONG TIN CA NHAN / DOI MAT KHAU) */}
        <div style={{ display: 'flex', gap: '12px', marginBottom: '20px' }}>
          <button
            type="button"
            onClick={() => setActiveTab('thong_tin')}
            style={{
              padding: '10px 20px',
              borderRadius: 'var(--bo-nho, 4px)',
              fontWeight: '700',
              fontSize: '0.95rem',
              cursor: 'pointer',
              border: activeTab === 'thong_tin' ? 'none' : '1px solid #d1d5db',
              background: activeTab === 'thong_tin' ? '#2d6a4f' : '#ffffff',
              color: activeTab === 'thong_tin' ? '#ffffff' : '#374151',
              boxShadow: activeTab === 'thong_tin' ? '0 2px 4px rgba(0,0,0,0.1)' : 'none',
              transition: 'all 0.2s ease',
            }}
          >
            Thông tin cá nhân
          </button>
          <button
            type="button"
            onClick={() => setActiveTab('doi_mat_khau')}
            style={{
              padding: '10px 20px',
              borderRadius: 'var(--bo-nho, 4px)',
              fontWeight: '700',
              fontSize: '0.95rem',
              cursor: 'pointer',
              border: activeTab === 'doi_mat_khau' ? 'none' : '1px solid #d1d5db',
              background: activeTab === 'doi_mat_khau' ? '#2d6a4f' : '#ffffff',
              color: activeTab === 'doi_mat_khau' ? '#ffffff' : '#374151',
              boxShadow: activeTab === 'doi_mat_khau' ? '0 2px 4px rgba(0,0,0,0.1)' : 'none',
              transition: 'all 0.2s ease',
            }}
          >
            Đổi mật khẩu
          </button>
        </div>

        {/* TAB CONTENT 1: THONG TIN CA NHAN */}
        {activeTab === 'thong_tin' && (
          <div style={{
            background: '#fff',
            padding: '28px',
            borderRadius: 'var(--bo-lon)',
            border: '1px solid var(--vien-nhat)',
            boxShadow: 'var(--bong-nho)'
          }}>
            <form onSubmit={xuLyCapNhat}>
              <div style={{ marginBottom: '16px' }}>
                <label style={{ display: 'block', fontWeight: '600', fontSize: '0.875rem', marginBottom: '6px' }}>
                  Vai trò tài khoản
                </label>
                <input
                  type="text"
                  disabled
                  value={profile?.role === 'sinh_vien' ? 'Sinh viên' : profile?.role === 'chu_tro' ? 'Chủ trọ' : 'Quản trị viên'}
                  style={{ width: '100%', padding: '10px 14px', borderRadius: 'var(--bo-vua)', border: '1px solid var(--vien-nhap)', background: 'var(--nen-xam)', textAlign: 'center', fontWeight: '500' }}
                />
              </div>

              <div style={{ marginBottom: '16px' }}>
                <label style={{ display: 'block', fontWeight: '600', fontSize: '0.875rem', marginBottom: '6px' }}>
                  Họ và tên
                </label>
                <input
                  type="text"
                  required
                  value={hoTen}
                  onChange={(e) => setHoTen(e.target.value)}
                  style={{ width: '100%', padding: '10px 14px', borderRadius: 'var(--bo-vua)', border: '1px solid var(--vien-nhap)' }}
                />
              </div>

              <div style={{ marginBottom: '16px' }}>
                <label style={{ display: 'block', fontWeight: '600', fontSize: '0.875rem', marginBottom: '6px' }}>
                  Số điện thoại
                </label>
                <input
                  type="tel"
                  required
                  value={soDienThoai}
                  onChange={(e) => setSoDienThoai(e.target.value)}
                  style={{ width: '100%', padding: '10px 14px', borderRadius: 'var(--bo-vua)', border: '1px solid var(--vien-nhap)' }}
                />
              </div>

              <div style={{ marginBottom: '24px' }}>
                <label style={{ display: 'block', fontWeight: '600', fontSize: '0.875rem', marginBottom: '6px' }}>
                  Email
                </label>
                <input
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  style={{ width: '100%', padding: '10px 14px', borderRadius: 'var(--bo-vua)', border: '1px solid var(--vien-nhap)' }}
                />
              </div>

              <div style={{ textAlign: 'center' }}>
                <button
                  type="submit"
                  disabled={dangCapNhat}
                  style={{
                    padding: '10px 24px',
                    background: 'var(--gradient-chinh)',
                    color: '#fff',
                    border: 'none',
                    borderRadius: 'var(--bo-vua)',
                    fontWeight: '700',
                    fontSize: '0.95rem',
                    cursor: 'pointer',
                    display: 'inline-block',
                  }}
                >
                  {dangCapNhat ? 'Đang lưu...' : 'Lưu thay đổi'}
                </button>
              </div>
            </form>

            {/* NUT XOA TAI KHOAN (CHI AP DUNG CHO CHU TRO VA SINH VIEN) */}
            {(profile?.role === 'sinh_vien' || profile?.role === 'chu_tro') && (
              <div style={{
                marginTop: '28px',
                paddingTop: '20px',
                borderTop: '1px dashed #fca5a5',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between',
                gap: '16px'
              }}>
                <div>
                  <div style={{ fontWeight: '700', color: '#dc2626', fontSize: '0.9rem' }}>
                    Xóa tài khoản
                  </div>
                  <div style={{ fontSize: '0.8rem', color: '#6b7280', marginTop: '2px' }}>
                    Xóa vĩnh viễn dữ liệu tài khoản cá nhân.
                  </div>
                </div>
                <button
                  type="button"
                  onClick={() => setHienModalXoa(true)}
                  style={{
                    padding: '8px 16px',
                    background: '#fee2e2',
                    color: '#dc2626',
                    border: '1px solid #fca5a5',
                    borderRadius: 'var(--bo-vua, 6px)',
                    fontWeight: '600',
                    fontSize: '0.85rem',
                    cursor: 'pointer',
                    whiteSpace: 'nowrap',
                    transition: 'all 0.2s ease',
                  }}
                >
                  Xóa tài khoản
                </button>
              </div>
            )}
          </div>
        )}

        {/* TAB CONTENT 2: DOI MAT KHAU */}
        {activeTab === 'doi_mat_khau' && (
          <div style={{
            background: '#fff',
            padding: '28px',
            borderRadius: 'var(--bo-lon)',
            border: '1px solid var(--vien-nhat)',
            boxShadow: 'var(--bong-nho)',
          }}>
            <form onSubmit={xuLyDoiMatKhau}>
              {/* Mat khau cu */}
              <div style={{ marginBottom: '16px' }}>
                <label style={{ display: 'block', fontWeight: '600', fontSize: '0.875rem', marginBottom: '6px' }}>
                  Mật khẩu hiện tại
                </label>
                <div style={{ position: 'relative' }}>
                  <input
                    type={hienMatKhauCu ? 'text' : 'password'}
                    required
                    value={matKhauCu}
                    onChange={(e) => setMatKhauCu(e.target.value)}
                    placeholder="Nhập mật khẩu hiện tại"
                    style={{ width: '100%', padding: '10px 44px 10px 14px', borderRadius: 'var(--bo-vua)', border: '1.5px solid var(--vien-nhap)', boxSizing: 'border-box', fontSize: '0.95rem' }}
                  />
                  <button
                    type="button"
                    onClick={() => setHienMatKhauCu(!hienMatKhauCu)}
                    style={{ position: 'absolute', right: '8px', top: '50%', transform: 'translateY(-50%)', background: 'none', border: 'none', padding: '6px', cursor: 'pointer', color: 'var(--chu-phu)', display: 'flex', alignItems: 'center' }}
                    title={hienMatKhauCu ? 'Ẩn mật khẩu' : 'Hiện mật khẩu'}
                  >
                    {hienMatKhauCu ? (
                      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                        <path d="M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 8 11 8a18.5 18.5 0 0 1-2.16 3.19m-6.72-1.07a3 3 0 1 1-4.24-4.24"></path>
                        <line x1="1" y1="1" x2="23" y2="23"></line>
                      </svg>
                    ) : (
                      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                        <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path>
                        <circle cx="12" cy="12" r="3"></circle>
                      </svg>
                    )}
                  </button>
                </div>
              </div>

              {/* Mat khau moi */}
              <div style={{ marginBottom: '16px' }}>
                <label style={{ display: 'block', fontWeight: '600', fontSize: '0.875rem', marginBottom: '6px' }}>
                  Mật khẩu mới
                </label>
                <div style={{ position: 'relative' }}>
                  <input
                    type={hienMatKhauMoi ? 'text' : 'password'}
                    required
                    minLength={6}
                    value={matKhauMoi}
                    onChange={(e) => setMatKhauMoi(e.target.value)}
                    placeholder="Ít nhất 6 ký tự"
                    style={{ width: '100%', padding: '10px 44px 10px 14px', borderRadius: 'var(--bo-vua)', border: '1.5px solid var(--vien-nhap)', boxSizing: 'border-box', fontSize: '0.95rem' }}
                  />
                  <button
                    type="button"
                    onClick={() => setHienMatKhauMoi(!hienMatKhauMoi)}
                    style={{ position: 'absolute', right: '8px', top: '50%', transform: 'translateY(-50%)', background: 'none', border: 'none', padding: '6px', cursor: 'pointer', color: 'var(--chu-phu)', display: 'flex', alignItems: 'center' }}
                    title={hienMatKhauMoi ? 'Ẩn mật khẩu' : 'Hiện mật khẩu'}
                  >
                    {hienMatKhauMoi ? (
                      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                        <path d="M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 8 11 8a18.5 18.5 0 0 1-2.16 3.19m-6.72-1.07a3 3 0 1 1-4.24-4.24"></path>
                        <line x1="1" y1="1" x2="23" y2="23"></line>
                      </svg>
                    ) : (
                      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                        <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path>
                        <circle cx="12" cy="12" r="3"></circle>
                      </svg>
                    )}
                  </button>
                </div>
              </div>

              {/* Xac nhan mat khau moi */}
              <div style={{ marginBottom: '24px' }}>
                <label style={{ display: 'block', fontWeight: '600', fontSize: '0.875rem', marginBottom: '6px' }}>
                  Xác nhận mật khẩu mới
                </label>
                <div style={{ position: 'relative' }}>
                  <input
                    type={hienXacNhan ? 'text' : 'password'}
                    required
                    value={xacNhanMatKhauMoi}
                    onChange={(e) => setXacNhanMatKhauMoi(e.target.value)}
                    placeholder="Nhập lại mật khẩu mới"
                    style={{ width: '100%', padding: '10px 44px 10px 14px', borderRadius: 'var(--bo-vua)', border: '1.5px solid var(--vien-nhap)', boxSizing: 'border-box', fontSize: '0.95rem' }}
                  />
                  <button
                    type="button"
                    onClick={() => setHienXacNhan(!hienXacNhan)}
                    style={{ position: 'absolute', right: '8px', top: '50%', transform: 'translateY(-50%)', background: 'none', border: 'none', padding: '6px', cursor: 'pointer', color: 'var(--chu-phu)', display: 'flex', alignItems: 'center' }}
                    title={hienXacNhan ? 'Ẩn mật khẩu' : 'Hiện mật khẩu'}
                  >
                    {hienXacNhan ? (
                      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                        <path d="M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 8 11 8a18.5 18.5 0 0 1-2.16 3.19m-6.72-1.07a3 3 0 1 1-4.24-4.24"></path>
                        <line x1="1" y1="1" x2="23" y2="23"></line>
                      </svg>
                    ) : (
                      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                        <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path>
                        <circle cx="12" cy="12" r="3"></circle>
                      </svg>
                    )}
                  </button>
                </div>
              </div>

              <div style={{ textAlign: 'center' }}>
                <button
                  type="submit"
                  disabled={dangDoiMatKhau}
                  style={{
                    padding: '10px 24px',
                    background: 'var(--gradient-chinh)',
                    color: '#fff',
                    border: 'none',
                    borderRadius: 'var(--bo-vua)',
                    fontWeight: '700',
                    fontSize: '0.95rem',
                    cursor: 'pointer',
                    display: 'inline-block',
                  }}
                >
                  {dangDoiMatKhau ? 'Đang xử lý...' : 'Đổi mật khẩu'}
                </button>
              </div>
            </form>
          </div>
        )}
      </div>
      {/* MODAL XAC NHAN XOA TAI KHOAN */}
      {hienModalXoa && (
        <div style={{
          position: 'fixed',
          inset: 0,
          background: 'rgba(0, 0, 0, 0.5)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          zIndex: 9999,
          padding: '16px',
        }}>
          <div style={{
            background: '#fff',
            borderRadius: 'var(--bo-lon, 12px)',
            maxWidth: '440px',
            width: '100%',
            padding: '24px',
            boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
          }}>
            <h3 style={{ fontSize: '1.15rem', fontWeight: '700', color: '#dc2626', marginBottom: '12px' }}>
              Xác nhận xóa tài khoản?
            </h3>
            <p style={{ fontSize: '0.9rem', color: '#4b5563', lineHeight: '1.5', marginBottom: '20px' }}>
              Bạn có chắc chắn muốn xóa tài khoản <strong>{profile?.ho_ten}</strong> ({profile?.so_dien_thoai}) không?
              Tất cả dữ liệu cá nhân, bài đăng và lịch hẹn liên quan sẽ bị xóa vĩnh viễn và <strong>không thể khôi phục</strong>.
            </p>

            <div style={{ display: 'flex', gap: '12px', justifyContent: 'flex-end' }}>
              <button
                type="button"
                disabled={dangXoaTaiKhoan}
                onClick={() => setHienModalXoa(false)}
                style={{
                  padding: '9px 18px',
                  borderRadius: 'var(--bo-vua, 6px)',
                  border: '1px solid #d1d5db',
                  background: '#fff',
                  color: '#374151',
                  fontWeight: '600',
                  fontSize: '0.875rem',
                  cursor: 'pointer',
                }}
              >
                Hủy
              </button>
              <button
                type="button"
                disabled={dangXoaTaiKhoan}
                onClick={xuLyXoaTaiKhoan}
                style={{
                  padding: '9px 18px',
                  borderRadius: 'var(--bo-vua, 6px)',
                  border: 'none',
                  background: '#dc2626',
                  color: '#fff',
                  fontWeight: '600',
                  fontSize: '0.875rem',
                  cursor: 'pointer',
                }}
              >
                {dangXoaTaiKhoan ? 'Đang xóa...' : 'Xóa vĩnh viễn'}
              </button>
            </div>
          </div>
        </div>
      )}
    </LayoutTaiKhoan>
  );
}
